### ISSUE TITLE
Can't merge class with props

### ISSUE THREAD

**Issue by steadicat** [ladderlife/om-css#11]
When passing props to a child while adding a class, the class doesn't get applied correctly. The following doesn't work, the class name applied is missing the component name (`__root`).

``` clojure
(defcomponent component2 [props children]
  [[:.root {:color :purple}]]
  (dom/div
   (merge props {:class :root})
   "purple"))
```

**Comment by anmonteiro** [comment]
fixed e4f64809171fab560c3576452825cddccefd476b
