### ISSUE TITLE
Allow :class to be a map of symbol to boolean

### ISSUE THREAD

**Issue by steadicat** [ladderlife/om-css#13]
It would be great if it were possible to do this:

``` clojure
{:class {:red    (= color "red")}
         :blue   (= color "blue")
         :white  (= color "white")}}
```

Every key whose value evaluates to true would be applied. This is a very useful pattern in React.

**Comment by anmonteiro** [comment]
I think this is possible to do in plain Clojurescript.
Do you have a failing case?

**Comment by steadicat** [comment]
I assumed it wouldn't be possible in component code because it would mess up the preprocessing. A few tests seem to suggest that's the case. See #15 and #16.

**Comment by steadicat** [comment]
I’m ok leaving support for this outside the scope of this library.
