### ISSUE TITLE
Variables from outer scope don't work inside props literal

### ISSUE THREAD

**Issue by steadicat** [ladderlife/om-css#20]
``` clojure
(let [dir "even"]
  (dom/div
    {:class (if (= dir "even") [:even] [])}))
```

In this case `:even` never gets applied. It seems the value of `dir` is not correctly propagated inside the scope of the props literal.

It works correctly if I move the `if` to the outside:

``` clojure
(let [dir "even"]
  (dom/div
    (if (= dir "even") {:class [:even]} {:class []}))
```

**Comment by anmonteiro** [comment]
fixed db84092fd3f287bd85f33ef92ec5d14d1da9016d
