### ISSUE TITLE
User-defined variables can't be used with :refer syntax

### ISSUE THREAD

**Issue by mikekap** [ladderlife/om-css#26]
The given example doesn't work if the variables are referenced in `defcomponent` via `:refer` rather than `:as`. Simplest example (sorry haven't checked it works entirely):

``` clojure
(ns consts)

(def font-size {:font-size "12px"})

(ns page
 (:require
  [om-css.dom :as dom]
  [om-css.core :refer-macros [defcomponent]]
  [consts :refer [font-size]]))

(defcomponent comp [props children]
 [:.style font-size]
 (dom/div {:class :style} "Hello"))
```

gives compile errors like `Unable to resolve symbol: font-size in this context`. When using an explicit namespace reference, everything seems to work.

This isn't too big of a deal, but is _very_ annoying when you need to use `garden.units`.

**Comment by anmonteiro** [comment]
fixed b64b58e77248603b75bd7908e85e2622dd50b823
