### ISSUE TITLE
Support merging with regular class-names

### ISSUE THREAD

**Issue by steadicat** [ladderlife/om-css#3]
It would be helpful if it were possible to mix and match `:class` attributes with regular `:class-name`s. This would aid migrations and allow the use of some global CSS classes (which could be useful in certain cases):

``` clojure
(defcomponent test [props children]
  [[:.root {:color :red}]]
  (om/div {:class :root :class-name "inline-block"} "test"))
```

**Comment by anmonteiro** [comment]
fixed 1ecf3f6ece77a9e6c59a988deea7471b3f922654
