### ISSUE TITLE
Let expressions break preprocessing

### ISSUE THREAD

**Issue by steadicat** [ladderlife/om-css#4]
If there's a `let` expression anywhere in your component, a few things break. Classes don't get added, and any component without props or children (e.g. `(dom/hr)`) throws a warning.

E.g.

``` clojure
(defcomponent component2
  [props children]
  [[:.root {:color :purple}]
   [:.active {:font-weight :bold}]
   [:.section {:color :green}]]
  (let [x true]
    (dom/div
     {:class [:root :active]}
     "div with class root"
     (dom/hr)
     (dom/section {:class :section}
                  "section with class :section"
                  children))))
```

This throws a warning (`Compile Warning - Wrong number of args (0) passed to om-css.dom/hr`), and all CSS classes are gone. If I remove the `let` statement, everything works fine.

**Comment by anmonteiro** [comment]
fixed c42d9e5e8f4cdcb9c297264f7b67d1590d070f4a
