### ISSUE TITLE
Cannot assign classes to child components

### ISSUE THREAD

**Issue by steadicat** [ladderlife/om-css#7]
A common pattern in React is to style child components by assigning CSS classes to them, as if they were regular DOM elements. The child is responsible for passing down the props to the final DOM element so it gets correctly applied. I couldn't find a way to do this with om-css:

``` clojure
(defcomponent component1
  [{:keys [class] :as props} children]
  [:.root {:color :purple}]
  (dom/div
   {:class (concat (props :class) [:root])}
   "class is now [:root :root], parent's class is lost"))

(defcomponent component2
  [props children]
  [:.root {:text-decoration :underline}]
  (component2 {:class [:root]}))
```

**Comment by anmonteiro** [comment]
fixed 8bfaa6e1c8c2b437cd89900380664221baa3029f
