### ISSUE TITLE
defcomponent incompatible with om.dom

### ISSUE THREAD

**Issue by steadicat** [ladderlife/om-css#8]
In order to migrate to om-css, I need to be able to use regular components that use `om.dom` inside of om-css components. For example, I should be able to do this:

``` clojure
(defcomponent component2 [props children]
  (om-dom/div {:class-name "test"} "test"))
```

The above throws an error.

It's ok if the om-css styles don't work for components using `om.dom`, because these components rely on the standard `class-name` prop.

**Comment by anmonteiro** [comment]
fixed e8807e1e9864a7c338c0566fc31a579d56408e6c
